### PR TITLE
Added static file support in golang-middleware

### LINKED ISSUE #7: No static file support in golang-middleware
## Expected behaviour

Static files such as Golang HTML templates or similar assets can be read and served by the function

## Current behaviour

Static files such as Golang HTML templates are not present in the function image

### PR DESCRIPTION
**Pull request by zbblanton**
## Description
Added the command to copy static files along with chown to own the app folder. Fixes #7.

## How Has This Been Tested?
Tested by creating a function using the golang-middleware template and adding files other than handler.go. Then built the function and used docker run to start the container and manually verified the files were copied.

Not tested on ARM. No hardware to test with.

## Checklist:
I have:
- [ ] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by zbblanton** [comment]
PR for #7

**Comment by rgee0** [comment]
Thanks Zachary.  Can you edit the description to include `Fixes #7` please?  This just helps us keep issues in check.

**Comment by alexellis** [comment]
> Not tested on ARM. No hardware to test with.

How have you tested it then?

Alex

**Comment by zbblanton** [comment]
Updated the description @rgee0. 

Added how I tested manually @alexellis.

**Comment by alexellis** [comment]
Please make the changes for the armhf templates also. Send a GitHub repo which shows this working so that we can have someone else verify from the Slack community in #arm-and-pi before merging. 

Alex

**Comment by alexellis** [comment]
@zbblanton please can you finish your PR? It's been around 8 weeks since we spoke last.

**Comment by alexellis** [comment]
I'll finish this personally. Not sure what happened here 👎

**Pull request merged**
