### PR TITLE
Bump of-watchdog version to 0.4.2

### PR DESCRIPTION
**Pull request by rdimitrov**
Signed-off-by: Radoslav Dimitrov <rdimitrow@gmail.com>

## Description
Bump of-watchdog version to 0.4.2

## How Has This Been Tested?

Not tested yet on ARM due to a lack of direct access to such system at the moment.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Review by alexellis — APPROVED** [review]
LGTM

**Comment by alexellis** [comment]
Cc @rgee0 for your OFC function.

**Comment by alexellis** [comment]
Thanks for the PR :)

**Comment by rgee0** [comment]
Nice work
```
HTTP/2 200 
server: nginx/1.13.12
date: Sun, 11 Nov 2018 08:48:18 GMT
content-type: application/cloudevents+json
content-length: 299
x-call-id: 48ea8718-8b78-4e7c-a8c3-e1bc17510e8b
x-duration-seconds: 0.001025
x-start-time: 1541926097990252488
strict-transport-security: max-age=15724800; includeSubDomains
```

**Pull request merged**
